# Setup
title:               "Julian Qi"
tagline:             "life is wonderful"
description:         "Julian Qi's personal blog."
url:                 https://julianqi.github.io
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Julian Qi
  url:               https://julianqi.github.io
  email:             julian.qi@outlook.com

# Custom vars
version:             1.0.0
