# Setup
title:               'Julian Qi'
tagline:             'life is beautiful'
description:         'Julian Qi's personal blog.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Julian Qi
  url:               https://julianqi.github.io
  email:             julian.qi@outlook.com

# Custom vars
version:             1.0.0
